dataset_root: /root/data1/Datasets/CSLR/PHOENIX-2014/phoenix-2014-multisigner
dict_path: ./preprocess/phoenix2014/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: phoenix2014-groundtruth
